using Content.Client.UserInterface.Controls;
using Content.Shared._WL.Languages;
using Content.Shared._WL.MedicalRecords;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client._WL.MedicalRecords;

[GenerateTypedNameReferences]
public sealed partial class MedicalRecordsConsoleWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public Action<uint?>? OnKeySelected;
    public Action<uint>? OnPrinted;
    public Action<StationRecordFilterType, string>? OnFiltersChanged;
    private uint? _selectedKey;

    public MedicalRecordsConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            FilterType.AddItem(GetTypeFilterLocals(item), (int)item);
        }

        RecordListing.OnItemSelected += args =>
        {
            if (RecordListing[args.ItemIndex].Metadata is not uint cast)
                return;

            OnKeySelected?.Invoke(cast);
        };

        RecordListing.OnItemDeselected += _ =>
        {
            OnKeySelected?.Invoke(null);
        };

        FilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType)eventArgs.Id;
            FilterListingOfRecords(FilterText.Text);
        };

        FilterText.OnTextEntered += args =>
        {
            FilterListingOfRecords(args.Text);
        };

        PrintButton.OnPressed += _ =>
        {
            PrintButton.Disabled = true;
            if (_selectedKey != null)
                OnPrinted?.Invoke(_selectedKey.Value);
        };
    }

    public void UpdateState(MedicalRecordsConsoleState state)
    {
        if (state.Filter != null && state.Filter.Value != FilterText.Text)
        {
            FilterText.Text = state.Filter.Value;
        }

        _selectedKey = state.SelectedKey;
        FilterType.SelectId((int)(state.Filter?.Type ?? StationRecordFilterType.Name));
        NoRecords.Visible = state.RecordListing == null || state.RecordListing.Count == 0;
        PopulateRecordListing(state.RecordListing);

        var selected = _selectedKey != null;
        PersonContainer.Visible = selected;
        RecordUnselected.Visible = !selected;

        if (state.StationRecord != null)
        {
            PopulateRecordContainer(state.StationRecord);
        }

        PrintButton.Disabled = !state.CanPrintRecords;
    }

    private void PopulateRecordListing(Dictionary<uint, string>? listing)
    {
        if (listing == null)
        {
            RecordListing.Clear();
            return;
        }

        var entries = listing.Select(i => new ItemList.Item(RecordListing)
        {
            Text = i.Value,
            Metadata = i.Key
        }).ToList();

        entries.Sort((a, b) => string.Compare(a.Text, b.Text, StringComparison.Ordinal));
        RecordListing.SetItems(entries, (a, b) => string.Compare(a.Text, b.Text));
    }

    private void PopulateRecordContainer(GeneralStationRecord stationRecord)
    {
        var na = Loc.GetString("generic-not-available-shorthand");
        PersonName.Text = stationRecord.Name;
        PersonJob.Text = stationRecord.JobTitle ?? na;
        PersonPrints.Text = stationRecord.Fingerprint ?? na;
        PersonDna.Text = stationRecord.DNA ?? na;

        MedicalRecordText.SetMessage(FormattedMessage.FromMarkupOrThrow(
            GenerateMedicalRecord(stationRecord)));
    }

    private string GenerateMedicalRecord(GeneralStationRecord stationRecord)
    {
        string languages = string.Empty;

        for (int i = 0; i < stationRecord.Languages.Count; i++)
        {
            languages += Loc.GetString(_prototypeManager.Index<LanguagePrototype>(stationRecord.Languages[i]).Name);

            if (i != stationRecord.Languages.Count - 1)
                languages += ", ";
            else
                languages += ".";
        }

        var medicalRecord = $"""
                {Loc.GetString("records-full-name-edit")} {(!string.IsNullOrEmpty(stationRecord.Fullname)
                ? stationRecord.Fullname : stationRecord.Name)}
                {Loc.GetString("records-date-of-birth-edit")}  {(!string.IsNullOrEmpty(stationRecord.DateOfBirth)
                ? stationRecord.DateOfBirth : Loc.GetString("generic-not-available-shorthand"))}
                {Loc.GetString("records-species")} {Loc.GetString(_prototypeManager.Index<SpeciesPrototype>(stationRecord.Species).Name)}
                {Loc.GetString("records-height", ("height", stationRecord.Height))}
                {Loc.GetString("records-language")} {languages}
                {(!string.IsNullOrEmpty(stationRecord.MedicalRecord) ? stationRecord.MedicalRecord
                : Loc.GetString("medical-records-console-no-record"))}
                """;

        return medicalRecord;
    }

    private void FilterListingOfRecords(string text = "")
    {
        OnFiltersChanged?.Invoke((StationRecordFilterType)FilterType.SelectedId, text);
    }

    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"medical-records-{type.ToString().ToLower()}-filter");
    }
}
