using Content.Client.Message;
using Content.Shared._WL.Turrets;
using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WL.Turrets;

[GenerateTypedNameReferences]
public sealed partial class TurretMinderConsoleWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;

    private readonly SpriteSystem _sprite;

    public event Action<NetEntity>? RideButtonPressed;

    public TurretMinderConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entMan.System<SpriteSystem>();
    }

    public void UpdateState(TurretMinderConsoleBoundUserInterfaceState state)
    {
        ButtonsContainer.RemoveAllChildren();

        if (state.NetEntities.Count == 0)
        {
            ButtonsContainer.AddChild(new Label()
            {
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Center,
                Text = Loc.GetString("turret-minder-no-guns")
            });

            return;
        }

        foreach (var entity in state.NetEntities)
        {
            ButtonsContainer.AddChild(GenerateButton(entity.Key, entity.Value));
        }
    }

    public BoxContainer GenerateButton(NetEntity entity, TurretMinderConsoleBUIStateEntry entry)
    {
        var main = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new(5),
        };

        var ent = _entMan.GetEntity(entity);
        var name = ent.IsValid() ? Identity.Name(ent, _entMan) : Loc.GetString("generic-unknown-title");

        var labelBoxContainer = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal
        };

        var label = new Label()
        {
            Text = name,
            Margin = new(0, 0, 5, 0)
        };

        var addressLabel = new RichTextLabel()
        {
            Margin = new(0, 0, 20, 0)
        };
        addressLabel.SetMarkup("[color=gray]" + entry.Address + "[/color]");

        labelBoxContainer.AddChild(label);
        labelBoxContainer.AddChild(addressLabel);

        var button = new Button()
        {
            Text = Loc.GetString("turret-minder-get-control")
        };
        button.OnPressed += (args) => RideButtonPressed?.Invoke(entity);

        if (entry.Disabled)
        {
            button.Disabled = true;
            button.Text = Loc.GetString("turret-minder-unavailable");
        }

        if (entry.Prototype != null)
        {
            var spriteView = new TextureRect()
            {
                Margin = new(0, 0, 5, 0),
                TextureScale = new(0.8f, 0.8f),
                Texture = _sprite.Frame0(_protoMan.Index(entry.Prototype))
            };

            main.AddChild(spriteView);
        }

        main.AddChild(labelBoxContainer);
        main.AddChild(button);

        return main;
    }
}
