using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._WL.CharacterInformation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._WL.CharacterInformation;

[GenerateTypedNameReferences]
public sealed partial class CharacterInformationWindow : FancyWindow
{
    [Dependency] private IEntityManager _entity = default!;

    private float _accumulatedTime;

    public CharacterInformationWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _accumulatedTime += args.DeltaSeconds;
        CharSprite.OverrideDirection = (Direction)((int)_accumulatedTime % 4 * 2);
    }

    public void UpdateState(CharacterInformationBuiState state)
    {
        CharSprite.SetEntity(_entity.GetEntity(state.Uid));
        NameLabel.SetMarkup($"[bold]{state.CharacterName}[/bold]");

        FlavorText.SetMessage(!string.IsNullOrEmpty(state.FlavorText)
            ? state.FlavorText
            : Loc.GetString("character-information-ui-no-flavor-text"));

        OocText.SetMessage(!string.IsNullOrEmpty(state.OocText)
            ? state.OocText
            : Loc.GetString("character-information-ui-no-ooc-text"));

        SetWidth = Size.X + 0.1f;
    }
}
