using Content.Client.UserInterface.Controls;
using Content.Shared.Audio.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using RRange = Robust.Client.UserInterface.Controls.Range;

namespace Content.Client.Audio.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class JukeboxMenu : FancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;
    private AudioSystem _audioSystem;

    /// <summary>
    /// Are we currently 'playing' or paused for the play / pause button.
    /// </summary>
    private bool _playState;

    /// <summary>
    /// True if playing, false if paused.
    /// </summary>
    public event Action<bool>? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action<ProtoId<JukeboxPrototype>>? OnSongSelected;
    public event Action<float>? SetTime;

    // WL-Changes-start
    public event Action<float>? VolumeChanged;

    private EntityUid? _audio;
    // WL-Changes-end

    private float _lockTimer;

    public JukeboxMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();

        // WL-Changes-start
        MusicList.SearchBar = SearchLineEdit;
        MusicList.DataFilterCondition += (input, listData) =>
        {
            return listData is JukeboxListData data &&
                (data.Name.Contains(input, StringComparison.CurrentCultureIgnoreCase)
                    || data.Author?.Contains(input, StringComparison.CurrentCultureIgnoreCase) == true
                    || data.JukeboxPrototype.Contains(input, StringComparison.CurrentCultureIgnoreCase));
        };

        MusicList.ItemPressed += (buttonEv, listData) =>
        {
            if (listData is not JukeboxListData data)
                return;

            OnSongSelected?.Invoke(data.JukeboxPrototype);
        };

        MusicList.GenerateItem += (listData, button) =>
        {
            if (listData is not JukeboxListData data)
                return;

            var label = new Label()
            {
                Text = $"{data.Author} - {data.Name}",
                Margin = new Thickness(6, 0, 0, 0),
            };

            button.AddChild(label);
        };

        VolumeSlider.OnValueChanged += rrange =>
        {
            SetVolumeLabelValue(rrange.Value);
        };

        VolumeSlider.OnReleased += slider =>
        {
            VolumeChanged?.Invoke(slider.Value);
        };
        // WL-Changes-end

        PlayButton.OnPressed += args =>
        {
            OnPlayPressed?.Invoke(!_playState);
        };

        StopButton.OnPressed += args =>
        {
            OnStopPressed?.Invoke();
        };
        PlaybackSlider.OnReleased += PlaybackSliderKeyUp;

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio), force: true);
    }

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
    }

    private void PlaybackSliderKeyUp(Slider args)
    {
        SetTime?.Invoke(PlaybackSlider.Value);
        _lockTimer = 0.5f;
    }

    // WL-Changes-start
    public void SetVolumeLabelValue(float gain)
    {
        VolumeSliderValueLabel.Text = $"{(int)(gain * 100)}%";
        VolumeSlider.SetValueWithoutEvent(gain);
    }
    // WL-Changes-end

    /// <summary>
    /// Re-populates the list of jukebox prototypes available.
    /// </summary>
    public void Populate(IEnumerable<JukeboxPrototype> jukeboxProtos)
    {
        // WL-Changes-start
        var sortedList = jukeboxProtos
            .OrderBy(proto => proto.Author)
                .ThenBy(proto => proto.Name)
            .Select(proto => new JukeboxListData(proto.Author, proto.Name, proto.ID))
            .ToList();

        MusicList.PopulateList(sortedList);
        // WL-Changes-end
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;

        if (playing)
        {
            PlayButton.Text = Loc.GetString("jukebox-menu-buttonpause");
            return;
        }

        PlayButton.Text = Loc.GetString("jukebox-menu-buttonplay");
    }

    public void SetSelectedSong(/*WL-Changes-start*/string? author,/*WL-Changes-end*/ string name, float length)
    {
        SetSelectedSongText(SharedJukeboxSystem.GetSongRepresentation(author, name)); // WL-Changes

        PlaybackSlider.MaxValue = length;
        PlaybackSlider.SetValueWithoutEvent(0);
    }

    // WL-Changes-start
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateLockTimer(args);
        UpdateDurationLabel();
        UpdatePlaybackSlider();
        UpdatePlayPauseButton();
    }

    private void UpdateLockTimer(FrameEventArgs args)
    {
        if (_lockTimer > 0f)
            _lockTimer -= args.DeltaSeconds;

        PlaybackSlider.Disabled = _lockTimer > 0f;
    }

    private void UpdateDurationLabel()
    {
        if (!TryGetAudio(out var audio))
        {
            DurationLabel.Text = "00:00 / 00:00";
            return;
        }

        var current = TimeSpan.FromSeconds(audio.PlaybackPosition);
        var total = _audioSystem.GetAudioLength(audio.FileName);

        DurationLabel.Text = $"{current:mm\\:ss} / {total:mm\\:ss}";
    }

    private void UpdatePlaybackSlider()
    {
        if (PlaybackSlider.Grabbed)
            return;

        if (TryGetAudio(out var audio))
            PlaybackSlider.SetValueWithoutEvent(audio.PlaybackPosition);
        else
            PlaybackSlider.SetValueWithoutEvent(0f);
    }

    private void UpdatePlayPauseButton()
    {
        if (TryGetAudio(out var audio))
            SetPlayPauseButton(_audioSystem.IsPlaying(_audio, audio));
        else
            SetPlayPauseButton(false);
    }

    private bool TryGetAudio([NotNullWhen(true)] out AudioComponent? audio)
    {
        return _entManager.TryGetComponent(_audio, out audio);
    }
    // WL-Changes-end

    public void SetSelectedSongText(string? text)
    {
        if (!string.IsNullOrEmpty(text))
        {
            SongName.Text = text;
        }
        else
        {
            SongName.Text = "---";
        }
    }

    // WL-Changes-start
    public record JukeboxListData(string? Author, string Name, string JukeboxPrototype) : ListData;
    // WL-Changes-end
}
