using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._WL.Records
{
    [GenerateTypedNameReferences]
    public sealed partial class RecordsTab : Control
    {
        public Action<string>? OnMedicalRecordChanged;
        public Action<string>? OnSecurityRecordChanged;
        public Action<string>? OnEmploymentRecordChanged;
        public Action<string>? OnGeneralRecordNameChanged;
        public Action<string>? OnGeneralRecordAgeChanged;
        public Action<OptionButton.ItemSelectedEventArgs>? OnGeneralRecordConfederationChanged;
        public Action<string>? OnGeneralRecordCountryChanged;

        public RecordsTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            MedicalRecordInput.Placeholder = new Rope.Leaf(Loc.GetString("records-medical-placeholder"));
            SecurityRecordInput.Placeholder = new Rope.Leaf(Loc.GetString("records-security-placeholder"));
            EmploymentRecordInput.Placeholder = new Rope.Leaf(Loc.GetString("records-employment-placeholder"));

            MedicalRecordInput.OnTextChanged += _ => OnMedicalRecordChanged?.Invoke(Rope.Collapse(MedicalRecordInput.TextRope).Trim());
            SecurityRecordInput.OnTextChanged += _ => OnSecurityRecordChanged?.Invoke(Rope.Collapse(SecurityRecordInput.TextRope).Trim());
            EmploymentRecordInput.OnTextChanged += _ => OnEmploymentRecordChanged?.Invoke(Rope.Collapse(EmploymentRecordInput.TextRope).Trim());

            NameEdit.OnTextChanged += _ => OnGeneralRecordNameChanged?.Invoke(NameEdit.Text.Trim());
            AgeEdit.OnTextChanged += _ => OnGeneralRecordAgeChanged?.Invoke(AgeEdit.Text.Trim());
            CountryEdit.OnTextChanged += _ => OnGeneralRecordCountryChanged?.Invoke(CountryEdit.Text.Trim());

            ConfederationButton.OnItemSelected += obj => OnGeneralRecordConfederationChanged?.Invoke(obj);

            MedicalTemplateButton.OnPressed += _ => LoadMedicalTemplate();
            SecurityTemplateButton.OnPressed += _ => LoadSecurityTemplate();
            EmploymentTemplateButton.OnPressed += _ => LoadEmploymentTemplate();
        }

        private void LoadMedicalTemplate()
        {
            MedicalRecordInput.TextRope = new Rope.Leaf(Loc.GetString("records-medical-template"));
        }

        private void LoadSecurityTemplate()
        {
            SecurityRecordInput.TextRope = new Rope.Leaf(Loc.GetString("records-security-template"));
        }

        private void LoadEmploymentTemplate()
        {
            EmploymentRecordInput.TextRope = new Rope.Leaf(Loc.GetString("records-employment-template"));
        }
    }
}
